name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # each hour
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          user: adityabhatia
          template: classic

      - uses: lowlighter/metrics@latest
        name: achievements
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: adityabhatia
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      
          plugin_achievements_secrets: yes     
          plugin_achievements_display: compact 
          plugin_achievements_limit: 0         
    
      - uses: lowlighter/metrics@latest
        name: lines
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          user: adityabhatia